name: rate_my_app
description: Allows to kindly ask users to rate your app if custom conditions are met (eg. install time, number of launches, etc...).
version: 0.6.0
homepage: https://github.com/Skyost/RateMyApp

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6
  smooth_star_rating: ^1.0.4
  pedantic: ">=1.4.0 <1.9.1"
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.skyost.rate_my_app
    pluginClass: RateMyAppPlugin
